awk '{ if ($1 == 1) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR1.txt 
awk '{ if ($1 == 2) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR2.txt 
awk '{ if ($1 == 3) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR3.txt 
awk '{ if ($1 == 4) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR4.txt 
awk '{ if ($1 == 5) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR5.txt 
awk '{ if ($1 == 6) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR6.txt 
awk '{ if ($1 == 7) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR7.txt 
awk '{ if ($1 == 8) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR8.txt 
awk '{ if ($1 == 9) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR9.txt 
awk '{ if ($1 == 10) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR10.txt 
awk '{ if ($1 == 11) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR11.txt 
awk '{ if ($1 == 12) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR12.txt 
awk '{ if ($1 == 13) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR13.txt 
awk '{ if ($1 == 14) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR14.txt 
awk '{ if ($1 == 15) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR15.txt 
awk '{ if ($1 == 16) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR16.txt 
awk '{ if ($1 == 17) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR17.txt 
awk '{ if ($1 == 18) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR18.txt 
awk '{ if ($1 == 19) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR19.txt 
awk '{ if ($1 == 20) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR20.txt 
awk '{ if ($1 == 21) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR21.txt 
awk '{ if ($1 == 22) { print } }' TrueEightCellIV.sorted.CX_report.txt > TrueEightCellIV.sorted.CX_report_CHR22.txt 

awk '{ if ($1 == 1) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR1.txt 
awk '{ if ($1 == 2) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR2.txt 
awk '{ if ($1 == 3) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR3.txt 
awk '{ if ($1 == 4) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR4.txt 
awk '{ if ($1 == 5) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR5.txt 
awk '{ if ($1 == 6) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR6.txt 
awk '{ if ($1 == 7) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR7.txt 
awk '{ if ($1 == 8) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR8.txt 
awk '{ if ($1 == 9) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR9.txt 
awk '{ if ($1 == 10) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR10.txt 
awk '{ if ($1 == 11) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR11.txt 
awk '{ if ($1 == 12) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR12.txt 
awk '{ if ($1 == 13) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR13.txt 
awk '{ if ($1 == 14) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR14.txt 
awk '{ if ($1 == 15) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR15.txt 
awk '{ if ($1 == 16) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR16.txt 
awk '{ if ($1 == 17) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR17.txt 
awk '{ if ($1 == 18) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR18.txt 
awk '{ if ($1 == 19) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR19.txt 
awk '{ if ($1 == 20) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR20.txt 
awk '{ if ($1 == 21) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR21.txt 
awk '{ if ($1 == 22) { print } }' TrueEightCell.sorted.CX_report.txt > TrueEightCell.sorted.CX_report_CHR22.txt 

